# =============================================================================
# Netlify Build & Functions Configuration
# =============================================================================
# Ini memberitahu Netlify tentang pengaturan dasar build Anda.

[build]
  # Publish directory:
  # Ini adalah folder yang berisi file-file website Anda (frontend).
  # Semua yang ada di sini akan di-deploy dan dapat diakses publik.
  publish = "public"

  # Functions directory:
  # Ini adalah folder tempat Netlify akan mencari serverless functions (backend).
  functions = "netlify/functions"

# =============================================================================
# Netlify Redirects & Rewrites Configuration
# =============================================================================
# Bagian ini mengatur bagaimana Netlify menangani permintaan URL.

[[redirects]]
  # Aturan ini akan menangkap setiap permintaan yang dimulai dengan "/api/".
  # Contoh: /api/chat, /api/another_function
  from = "/api/*"

  # Permintaan tersebut akan dialihkan (rewrite) secara internal ke serverless function yang sesuai.
  # Contoh: permintaan ke "/api/chat" akan dieksekusi oleh file "/.netlify/functions/chat.js".
  # :splat adalah placeholder untuk semua yang cocok dengan tanda bintang (*).
  to = "/.netlify/functions/:splat"

  # Status 200 berarti ini adalah "rewrite", bukan "redirect".
  # URL di browser pengguna tidak akan berubah, membuat backend terasa seperti bagian dari situs utama.
  status = 200
