# Konfigurasi Build
[build]
  # BARIS INI WAJIB ADA: Memberitahu Netlify bahwa website Anda berada di folder "public"
  publish = "public"
  # Baris ini memberitahu Netlify di mana menemukan folder functions Anda
  functions = "netlify/functions"

# Konfigurasi Pengalihan (Redirect)
[[redirects]]
  # Mengalihkan semua permintaan yang dimulai dengan /api/
  from = "/api/*"
  # Ke fungsi yang sesuai. Jika URL adalah /api/chat, :splat akan menjadi "chat".
  # Hasilnya akan dialihkan ke /.netlify/functions/chat
  to = "/.netlify/functions/:splat"
  # Status 200 berarti pengalihan ini transparan bagi pengguna
  status = 200
