# =============================================================================
# Konfigurasi Build & Deploy Netlify
# =============================================================================

[build]
  # Publish directory:
  # WAJIB: Baris ini memberitahu Netlify bahwa folder "public" adalah
  # folder utama yang berisi semua file website (HTML, CSS, JS).
  publish = "public"

  # Functions directory:
  # Memberitahu Netlify di mana folder untuk serverless functions (backend) berada.
  functions = "netlify/functions"

# =============================================================================
# Aturan Pengalihan (Redirects & Rewrites)
# =============================================================================
# Bagian ini sangat penting untuk menghubungkan frontend ke backend.

[[redirects]]
  # Aturan ini akan menangkap setiap permintaan dari website Anda
  # yang dimulai dengan "/api/". Contoh: /api/chat
  from = "/api/*"

  # Permintaan tersebut akan dialihkan secara internal ke serverless function yang sesuai.
  # :splat adalah placeholder untuk apa pun yang cocok dengan tanda bintang (*).
  # Contoh: permintaan ke "/api/chat" akan dieksekusi oleh file di "/.netlify/functions/chat.js".
  to = "/.netlify/functions/:splat"

  # Status 200 berarti ini adalah "rewrite", bukan "redirect".
  # URL di browser pengguna tidak akan berubah, membuat backend terasa seperti 
  # bagian dari situs utama dan menghindari masalah CORS.
  status = 200
